//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class accessoryPayment
    {
        public string ID { get; set; }
        public string OrderID { get; set; }
        public string Gateway { get; set; }
        public float Amount { get; set; }
        public int Quantitty { get; set; }
        public string Product { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Account { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseDesc { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Returned_Reference { get; set; }
        public string IPAddress { get; set; }
        public string Charge_TransID { get; set; }
        public string Allocation_TransID { get; set; }
        public string Step_Status { get; set; }
        public string Email { get; set; }
        public string SessionID { get; set; }
        public string ModemType { get; set; }
        public Nullable<double> Gateway_Returned_Amount { get; set; }
        public string mobilephone { get; set; }
        public string productdesc { get; set; }
        public string voucher { get; set; }
        public int ConfirmCalled { get; set; }
    }
}
