//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int i_customer { get; set; }
        public int i_account { get; set; }
        public string id { get; set; }
        public Nullable<int> i_product { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public Nullable<int> billing_model { get; set; }
        public Nullable<System.DateTime> activation_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string blocked { get; set; }
        public Nullable<System.DateTime> last_usage { get; set; }
        public Nullable<System.DateTime> first_usage { get; set; }
        public Nullable<double> credit_limit { get; set; }
        public string email { get; set; }
        public Nullable<int> i_subscriber { get; set; }
        public string bill_status { get; set; }
        public Nullable<int> i_master_account { get; set; }
        public string subscriber_email { get; set; }
        public string batch_name { get; set; }
        public string baddr1 { get; set; }
        public string baddr2 { get; set; }
        public string baddr3 { get; set; }
        public string baddr4 { get; set; }
        public string baddr5 { get; set; }
        public string bcc { get; set; }
        public string city { get; set; }
        public string cont1 { get; set; }
        public string cont2 { get; set; }
        public string country { get; set; }
        public string faxnum { get; set; }
        public Nullable<System.DateTime> last_recharge { get; set; }
        public Nullable<int> life_time { get; set; }
        public string mac { get; set; }
        public string midinit { get; set; }
        public string note { get; set; }
        public Nullable<double> opening_balance { get; set; }
        public Nullable<System.DateTime> password_timestamp { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> zero_balance_date { get; set; }
        public string zip { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
    }
}
