//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNTS_FROM_PORTAONE
    {
        public decimal I_ACCOUNT { get; set; }
        public string ID { get; set; }
        public string PASSWORD { get; set; }
        public string H323_PASSWORD { get; set; }
        public decimal BALANCE { get; set; }
        public decimal OPENING_BALANCE { get; set; }
        public System.DateTime ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> ZERO_BALANCE_DATE { get; set; }
        public decimal I_CUSTOMER { get; set; }
        public decimal BILLING_MODEL { get; set; }
        public System.DateTime ACTIVATION_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public decimal I_PRODUCT { get; set; }
        public string BLOCKED { get; set; }
        public Nullable<System.DateTime> LAST_USAGE { get; set; }
        public Nullable<decimal> I_BATCH { get; set; }
        public decimal I_ENV { get; set; }
        public Nullable<decimal> LIFE_TIME { get; set; }
        public string REDIRECT_NUMBER { get; set; }
        public Nullable<decimal> CONTROL_NUMBER { get; set; }
        public string ISO_639_1 { get; set; }
        public decimal I_TIME_ZONE { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public string ISO_4217 { get; set; }
        public Nullable<decimal> REFUNDS { get; set; }
        public string LOGIN { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> PASSWORD_TIMESTAMP { get; set; }
        public decimal I_ACL { get; set; }
        public Nullable<decimal> I_SUBSCRIBER { get; set; }
        public string I_LANG { get; set; }
        public Nullable<decimal> UA_PROFILE_ID { get; set; }
        public string MAC { get; set; }
        public Nullable<System.DateTime> TIMER { get; set; }
        public string ECOMMERCE_ENABLED { get; set; }
        public string OUT_DATE_FORMAT { get; set; }
        public string OUT_TIME_FORMAT { get; set; }
        public string OUT_DATE_TIME_FORMAT { get; set; }
        public string IN_DATE_FORMAT { get; set; }
        public string IN_TIME_FORMAT { get; set; }
        public Nullable<decimal> I_VD_PLAN { get; set; }
        public Nullable<System.DateTime> LAST_RECHARGE { get; set; }
        public Nullable<decimal> I_MOH { get; set; }
        public string SERVICE_FLAGS { get; set; }
        public Nullable<decimal> I_MASTER_ACCOUNT { get; set; }
        public string BILL_STATUS { get; set; }
        public Nullable<decimal> I_ROUTING_PLAN { get; set; }
        public Nullable<decimal> I_DISTRIBUTOR { get; set; }
        public string MANAGEMENT_NUMBER { get; set; }
        public decimal PROFITABILITY { get; set; }
        public Nullable<decimal> I_CUSTOMER_SITE { get; set; }
        public Nullable<System.DateTime> FIRST_USAGE_TIME { get; set; }
        public decimal I_PASSPHRASE { get; set; }
        public string OVERRIDE_PRODUCT_VD_PLAN { get; set; }
        public Nullable<decimal> I_ACCOUNT_BALANCE_CONTROL_TYPE { get; set; }
        public Nullable<decimal> INACTIVITY_EXPIRE_TIME { get; set; }
    }
}
