//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto_Allocate_Subscribers
    {
        public int SettingID { get; set; }
        public int i_customer { get; set; }
        public int i_account { get; set; }
        public int AutoMove { get; set; }
        public int Priority { get; set; }
        public System.DateTime DateLastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public int Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    }
}
