//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoAllocation_Transactions
    {
        public int AllocateID { get; set; }
        public int AutoSettingID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public string OnlineID { get; set; }
        public string Status { get; set; }
        public Nullable<int> i_customer { get; set; }
        public Nullable<int> i_account { get; set; }
    }
}
