//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiometricsCustomersDetailsLog
    {
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string OwnerOfBiometricsDetails { get; set; }
        public Nullable<int> UpdatedOnCRM { get; set; }
        public string ComputerName { get; set; }
        public string IPAddress { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
