//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiometricsBonu
    {
        public int ID { get; set; }
        public Nullable<int> i_customer { get; set; }
        public Nullable<int> i_account { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string PaymentSource { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public string BonusType { get; set; }
        public string TransactionID { get; set; }
        public Nullable<int> i_product { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Granted { get; set; }
        public string macAddress { get; set; }
        public string Username { get; set; }
        public string cXDR { get; set; }
        public string aXDR { get; set; }
        public string aPaymentUID { get; set; }
        public string cPaymentUID { get; set; }
    }
}
