//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int BonusID { get; set; }
        public Nullable<int> i_customer { get; set; }
        public Nullable<int> i_account { get; set; }
        public string PPlatform { get; set; }
        public string PRefID { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public Nullable<double> BonusAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string BonusCategory { get; set; }
        public Nullable<int> AllocatePattern { get; set; }
        public Nullable<int> Allocated { get; set; }
        public Nullable<System.DateTime> DateFirstAllocated { get; set; }
        public Nullable<double> TotalAllocatedAmount { get; set; }
        public Nullable<int> AllocationCount { get; set; }
        public Nullable<System.DateTime> DateLastAllocated { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
