//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkVoucherDenomination
    {
        public int DenominationID { get; set; }
        public int i_customer { get; set; }
        public double Value { get; set; }
        public double Percentage { get; set; }
        public int MinimumCount { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
