//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkSMS_EmailLogs
    {
        public int LogID { get; set; }
        public string BatchNo { get; set; }
        public string SqlString { get; set; }
        public string BaseStations { get; set; }
        public string Sectors { get; set; }
        public string BaseStationStatus { get; set; }
        public string BaseStationAliveStatus { get; set; }
        public string EmailSubject { get; set; }
        public string EmailMessage { get; set; }
        public string EmailFrom { get; set; }
        public string FileName { get; set; }
        public string SMSContent { get; set; }
        public string SMSFrom { get; set; }
        public Nullable<int> EmailStatus { get; set; }
        public Nullable<int> SMSStatus { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> EmailDateSent { get; set; }
        public Nullable<System.DateTime> SMSDateSent { get; set; }
    }
}
