//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUMA_2012_2015_3
    {
        public decimal I_CUSTOMER { get; set; }
        public string CHARGED_QUANTITY { get; set; }
        public string CHARGED_AMOUNT { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
    }
}
