//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactExtensionBase
    {
        public System.Guid ContactId { get; set; }
        public string new_CityInstallationAddress { get; set; }
        public string new_CountryInstallationAddress { get; set; }
        public string new_CustomerName { get; set; }
        public Nullable<int> new_CustomerType { get; set; }
        public Nullable<System.DateTime> new_Date { get; set; }
        public string new_EMail2 { get; set; }
        public string new_Lead_ID { get; set; }
        public string new_Number { get; set; }
        public string new_NumberInstallationAddress { get; set; }
        public string new_POBox { get; set; }
        public string new_POBoxinstallationaddress { get; set; }
        public string new_PrimaryContact { get; set; }
        public Nullable<int> new_SalutationDropDown { get; set; }
        public Nullable<int> new_ServicePlan { get; set; }
        public string new_StateInstallationAddress { get; set; }
        public string new_StreetInstallationAddress { get; set; }
        public string new_SubscriberID { get; set; }
        public string new_TemporaryPassword { get; set; }
        public Nullable<int> new_TitleTmp { get; set; }
        public string new_UserNameTextField { get; set; }
        public string new_Website { get; set; }
        public Nullable<System.Guid> new_C_Prod { get; set; }
        public Nullable<int> new_ModemType { get; set; }
        public Nullable<int> new_TelesalesAgent { get; set; }
        public Nullable<int> new_EmailStatus { get; set; }
        public Nullable<int> new_CustomerCategory { get; set; }
        public string new_NextofKin { get; set; }
        public string new_NextofKinAddress { get; set; }
        public string new_NextofKinPhone { get; set; }
        public string new_RefererSubscriberID { get; set; }
        public string new_ReferalCode { get; set; }
        public string new_TransactionID { get; set; }
        public Nullable<bool> new_KYCVerified { get; set; }
        public Nullable<int> new_leadsource { get; set; }
        public Nullable<int> new_PromoType { get; set; }
        public Nullable<System.Guid> new_ImportedBy { get; set; }
    }
}
