//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditAccountExtension
    {
        public int AccountExtensionID { get; set; }
        public Nullable<int> i_customer { get; set; }
        public Nullable<double> amount { get; set; }
        public string source { get; set; }
        public string txnref { get; set; }
        public Nullable<System.DateTime> paymentdate { get; set; }
        public string StatusMsg { get; set; }
        public Nullable<System.DateTime> dateimplemented { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<int> charge { get; set; }
        public string process { get; set; }
        public Nullable<int> Status { get; set; }
        public string AccountIDs { get; set; }
        public string R_paymentUID { get; set; }
        public string R_AccountIDs { get; set; }
        public Nullable<double> R_Amount { get; set; }
        public Nullable<int> R_Status { get; set; }
        public Nullable<System.DateTime> R_Date { get; set; }
    }
}
