//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMFailedPayment
    {
        public int FailureID { get; set; }
        public string subscriber_id { get; set; }
        public string product_name { get; set; }
        public Nullable<double> amount { get; set; }
        public string transid { get; set; }
        public string transtype { get; set; }
        public string desc { get; set; }
        public string gway { get; set; }
        public Nullable<double> discount { get; set; }
        public string FailureError { get; set; }
        public Nullable<int> Retried { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public Nullable<System.DateTime> LastRetriedDate { get; set; }
        public Nullable<int> Success { get; set; }
        public Nullable<System.DateTime> SuccessDate { get; set; }
        public string ReceiptNo { get; set; }
        public string TransTable { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
