//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int i_customer { get; set; }
        public string salutation { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string midinit { get; set; }
        public string companyname { get; set; }
        public string baddr1 { get; set; }
        public string baddr2 { get; set; }
        public string baddr3 { get; set; }
        public string baddr4 { get; set; }
        public string baddr5 { get; set; }
        public string email { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string Password { get; set; }
        public string login { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string bill_status { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string bcc { get; set; }
        public string cont1 { get; set; }
        public string cont2 { get; set; }
        public string country { get; set; }
        public string note { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public string blocked { get; set; }
        public Nullable<int> KYCStatus { get; set; }
        public Nullable<int> hasStaffAcct { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string homephone { get; set; }
        public string occupation { get; set; }
        public string officeaddress { get; set; }
        public string jobtitle { get; set; }
        public string department { get; set; }
        public string manager { get; set; }
        public string managerphone { get; set; }
        public string assistant { get; set; }
        public string assistantphone { get; set; }
        public string maritalstatus { get; set; }
        public Nullable<System.DateTime> anniversary { get; set; }
        public string spousename { get; set; }
        public string nok { get; set; }
        public string nokphone { get; set; }
        public string nokaddress { get; set; }
        public string contactmethods { get; set; }
        public string identificationnumber { get; set; }
        public string monthlyincome { get; set; }
        public string favouriteinternetactivity { get; set; }
        public string CustomerType { get; set; }
        public string ModemType { get; set; }
        public Nullable<double> CreditLimit { get; set; }
    }
}
