//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERS250117
    {
        public decimal I_CUSTOMER { get; set; }
        public string REFNUM { get; set; }
        public string NAME { get; set; }
        public decimal BALANCE { get; set; }
        public string ISO_4217 { get; set; }
        public string COMPANYNAME { get; set; }
        public string SALUTATION { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDINIT { get; set; }
        public string LASTNAME { get; set; }
        public string BADDR1 { get; set; }
        public string BADDR2 { get; set; }
        public string BADDR3 { get; set; }
        public string BADDR4 { get; set; }
        public string BADDR5 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string NOTE { get; set; }
        public string CONT1 { get; set; }
        public string PHONE1 { get; set; }
        public string FAXNUM { get; set; }
        public string PHONE2 { get; set; }
        public string CONT2 { get; set; }
        public string EMAIL { get; set; }
        public string BCC { get; set; }
        public string SEND_STATISTICS { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public decimal I_CUSTOMER_TYPE { get; set; }
        public decimal I_BILLING_PERIOD { get; set; }
        public Nullable<decimal> I_TARIFF { get; set; }
        public decimal I_TIME_ZONE { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public Nullable<decimal> I_CREDIT_CARD { get; set; }
        public decimal I_ENV { get; set; }
        public Nullable<decimal> I_TEMPLATE { get; set; }
        public string TAX_ID { get; set; }
        public string BLOCKED { get; set; }
        public Nullable<decimal> I_REP { get; set; }
        public Nullable<decimal> MAX_ABBREVIATED_LENGTH { get; set; }
        public Nullable<System.DateTime> PASSWORD_TIMESTAMP { get; set; }
        public string OUT_DATE_FORMAT { get; set; }
        public string OUT_TIME_FORMAT { get; set; }
        public string OUT_DATE_TIME_FORMAT { get; set; }
        public string IN_DATE_FORMAT { get; set; }
        public string IN_TIME_FORMAT { get; set; }
        public decimal I_ACL { get; set; }
        public decimal OPENING_BALANCE { get; set; }
        public string I_LANG { get; set; }
        public Nullable<decimal> I_TARIFF_INCOMING { get; set; }
        public string CREDIT_LIMIT_WARNING { get; set; }
        public string CALLSHOP_ENABLED { get; set; }
        public Nullable<System.DateTime> BILLED_TO { get; set; }
        public Nullable<decimal> I_PARENT { get; set; }
        public Nullable<decimal> I_ROUTING_PLAN { get; set; }
        public Nullable<decimal> I_VD_PLAN { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> I_MOH { get; set; }
        public string SERVICE_FLAGS { get; set; }
        public decimal I_CUSTOMER_CLASS { get; set; }
        public string BP_CHARGE_CC { get; set; }
        public decimal UNALLOCATED_PAYMENTS { get; set; }
        public string BILL_STATUS { get; set; }
        public Nullable<decimal> DISCOUNT_RATE { get; set; }
        public Nullable<System.DateTime> TAXED_TO { get; set; }
        public Nullable<decimal> I_BILLING_PROCESSOR { get; set; }
        public string TAX_INFO { get; set; }
        public Nullable<System.DateTime> SUSPENSION_DELAY_DATE { get; set; }
        public string SEND_INVOICES { get; set; }
        public Nullable<System.DateTime> SHIFTED_BILLING_DATE { get; set; }
        public Nullable<decimal> SALE_COMMISSION_RATE { get; set; }
        public Nullable<decimal> PAYMENT_COMMISSION_RATE { get; set; }
        public Nullable<decimal> I_DISTRIBUTOR { get; set; }
        public decimal PROFITABILITY { get; set; }
        public string OVERRIDE_TARIFFS_ENABLED { get; set; }
        public Nullable<decimal> I_DO_BATCH { get; set; }
        public Nullable<decimal> I_NUMBER_SCOPE { get; set; }
        public Nullable<decimal> I_NUMBER_SCOPE_RESELLER { get; set; }
        public Nullable<decimal> PREVIOUS_CREDIT_LIMIT { get; set; }
        public Nullable<System.DateTime> CREDIT_LIMIT_UNTIL { get; set; }
        public string SUSPEND_ON_INSUFF_FUNDS { get; set; }
        public Nullable<decimal> NEW_I_BILLING_PERIOD { get; set; }
        public Nullable<decimal> NEW_I_TIME_ZONE { get; set; }
        public Nullable<System.DateTime> SCHEDULED_BILLING_CHANGE { get; set; }
        public Nullable<decimal> I_UI_TIME_ZONE { get; set; }
        public Nullable<System.DateTime> BUNDLE_BILLED_TO { get; set; }
        public decimal I_PASSPHRASE { get; set; }
        public Nullable<System.DateTime> DEACTIVATE_ON { get; set; }
        public Nullable<System.DateTime> RESTORE_ON { get; set; }
        public decimal I_BALANCE_CONTROL_TYPE { get; set; }
        public decimal I_OFFICE_TYPE { get; set; }
        public Nullable<decimal> I_MAIN_OFFICE { get; set; }
        public Nullable<System.DateTime> TERMINATE_ON { get; set; }
        public string GENERATE_INVOICE_EARLIER { get; set; }
        public string EMAIL_FROM { get; set; }
        public Nullable<decimal> I_SPEND_PLAN { get; set; }
        public string PDF_GENERATION_MODE { get; set; }
    }
}
