//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEmailChange
    {
        public int Change_ID { get; set; }
        public int i_customer { get; set; }
        public string Old_Email { get; set; }
        public string New_Email { get; set; }
        public string Email_UID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Source { get; set; }
        public Nullable<int> Validated { get; set; }
        public Nullable<System.DateTime> DateValidated { get; set; }
        public Nullable<int> FirstLogin { get; set; }
    }
}
