//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddressBase
    {
        public System.Guid ParentId { get; set; }
        public System.Guid CustomerAddressId { get; set; }
        public Nullable<int> AddressNumber { get; set; }
        public int ObjectTypeCode { get; set; }
        public Nullable<int> AddressTypeCode { get; set; }
        public string Name { get; set; }
        public string PrimaryContactName { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string PostOfficeBox { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> UTCOffset { get; set; }
        public Nullable<int> FreightTermsCode { get; set; }
        public string UPSZone { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Telephone1 { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> ShippingMethodCode { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public string Fax { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<int> ParentIdTypeCode { get; set; }
    }
}
