//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_LastPayments
    {
        public int i_customer { get; set; }
        public int i_account { get; set; }
        public Nullable<double> c_balance { get; set; }
        public Nullable<double> c_payment { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
    }
}
