//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Reminders
    {
        public int i_customer { get; set; }
        public int i_account { get; set; }
        public Nullable<System.DateTime> Daily1 { get; set; }
        public Nullable<System.DateTime> Daily2 { get; set; }
        public Nullable<System.DateTime> Daily3 { get; set; }
        public Nullable<System.DateTime> Volume1 { get; set; }
        public Nullable<System.DateTime> Volume2 { get; set; }
        public Nullable<System.DateTime> Volume3 { get; set; }
        public string Monthly { get; set; }
    }
}
