//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class swift_utilityEntities : DbContext
    {
        public swift_utilityEntities()
            : base("name=swift_utilityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accessoryPayment> accessoryPayments { get; set; }
        public DbSet<Account> Accounts { get; set; }
        public DbSet<ACCOUNTS_FROM_PORTAONE> ACCOUNTS_FROM_PORTAONE { get; set; }
        public DbSet<ASPStateTempApplication> ASPStateTempApplications { get; set; }
        public DbSet<ASPStateTempSession> ASPStateTempSessions { get; set; }
        public DbSet<Auto_Allocate_Subscribers> Auto_Allocate_Subscribers { get; set; }
        public DbSet<AutoAllocation_Transactions> AutoAllocation_Transactions { get; set; }
        public DbSet<AutoAllocation_Transactions_Orig> AutoAllocation_Transactions_Orig { get; set; }
        public DbSet<backup_171014_Vouchers> backup_171014_Vouchers { get; set; }
        public DbSet<backup_vouchers_181214> backup_vouchers_181214 { get; set; }
        public DbSet<Batch> Batches { get; set; }
        public DbSet<BiometricsAgent> BiometricsAgents { get; set; }
        public DbSet<BiometricsBonu> BiometricsBonus { get; set; }
        public DbSet<BiometricsBonusService> BiometricsBonusServices { get; set; }
        public DbSet<BiometricsCustomersDetailsLog> BiometricsCustomersDetailsLogs { get; set; }
        public DbSet<Bonus> Bonuses { get; set; }
        public DbSet<BulkSMS_EmailLogs> BulkSMS_EmailLogs { get; set; }
        public DbSet<BulkVoucherDenomination> BulkVoucherDenominations { get; set; }
        public DbSet<BulkVoucherFulfilment> BulkVoucherFulfilments { get; set; }
        public DbSet<BulkVoucherPurchaser> BulkVoucherPurchasers { get; set; }
        public DbSet<CHUMA_2012_2015_3> CHUMA_2012_2015_3 { get; set; }
        public DbSet<churnReason> churnReasons { get; set; }
        public DbSet<cluster> clusters { get; set; }
        public DbSet<ContactBase> ContactBases { get; set; }
        public DbSet<ContactExtensionBase> ContactExtensionBases { get; set; }
        public DbSet<coveragemap> coveragemaps { get; set; }
        public DbSet<CreditAccountExtension> CreditAccountExtensions { get; set; }
        public DbSet<CreditAccountsEmailAlertsCheck> CreditAccountsEmailAlertsChecks { get; set; }
        public DbSet<CreditAccountsNotification> CreditAccountsNotifications { get; set; }
        public DbSet<CreditLimitNotification> CreditLimitNotifications { get; set; }
        public DbSet<CRMFailedPayment> CRMFailedPayments { get; set; }
        public DbSet<CRMLoansRepayment> CRMLoansRepayments { get; set; }
        public DbSet<CrmParameter> CrmParameters { get; set; }
        public DbSet<CRMPayment> CRMPayments { get; set; }
        public DbSet<Customer_BlockUnblock> Customer_BlockUnblock { get; set; }
        public DbSet<Customer_Reminders> Customer_Reminders { get; set; }
        public DbSet<CustomerAddressBase> CustomerAddressBases { get; set; }
        public DbSet<CustomerEmailChange> CustomerEmailChanges { get; set; }
        public DbSet<CustomerIDNo> CustomerIDNoes { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Customers_LastPayments> Customers_LastPayments { get; set; }
        public DbSet<customers_lock> customers_lock { get; set; }
        public DbSet<CUSTOMERS250117> CUSTOMERS250117 { get; set; }
        public DbSet<CustomersEmailMessageLog> CustomersEmailMessageLogs { get; set; }
        public DbSet<CustomersEmailMessageLogs_Archive_3576844> CustomersEmailMessageLogs_Archive_3576844 { get; set; }
        public DbSet<CustomersEmailMessageLogs_Archive_9121744> CustomersEmailMessageLogs_Archive_9121744 { get; set; }
        public DbSet<CUSTOMERSEMAIL> CUSTOMERSEMAILS { get; set; }
        public DbSet<CustomUser> CustomUsers { get; set; }
        public DbSet<debby> debbies { get; set; }
        public DbSet<debby2> debby2 { get; set; }
        public DbSet<DebitAccountsEmailAlertsCheck> DebitAccountsEmailAlertsChecks { get; set; }
        public DbSet<DebitAccountsNotification> DebitAccountsNotifications { get; set; }
        public DbSet<DebitAccountsNotifications_bkp_081214> DebitAccountsNotifications_bkp_081214 { get; set; }
        public DbSet<Deleted_Vouchers> Deleted_Vouchers { get; set; }
        public DbSet<Escravos_Customers_Account> Escravos_Customers_Account { get; set; }
        public DbSet<EscravosRefundCustomer> EscravosRefundCustomers { get; set; }
        public DbSet<ExpirationDate_InvalidExtensions> ExpirationDate_InvalidExtensions { get; set; }
        public DbSet<FacebookEmailLogin> FacebookEmailLogins { get; set; }
        public DbSet<FailedPayments_Feb1to52013> FailedPayments_Feb1to52013 { get; set; }
        public DbSet<FailedPortaOneTransactionNote> FailedPortaOneTransactionNotes { get; set; }
        public DbSet<HotlinedFundedAccountsSessionExtension> HotlinedFundedAccountsSessionExtensions { get; set; }
        public DbSet<HotSpotPayment> HotSpotPayments { get; set; }
        public DbSet<InternetTest_Feedback> InternetTest_Feedback { get; set; }
        public DbSet<InterSwitch_Data> InterSwitch_Data { get; set; }
        public DbSet<Interswitch_Paydirect> Interswitch_Paydirect { get; set; }
        public DbSet<IrokoTVCode_Exceptions> IrokoTVCode_Exceptions { get; set; }
        public DbSet<IrokoTVCode> IrokoTVCodes { get; set; }
        public DbSet<IVRPayment> IVRPayments { get; set; }
        public DbSet<KYCBlockUnbock> KYCBlockUnbocks { get; set; }
        public DbSet<KYCDeferment> KYCDeferments { get; set; }
        public DbSet<KYCRejectReason> KYCRejectReasons { get; set; }
        public DbSet<KYCUpload> KYCUploads { get; set; }
        public DbSet<LoanException> LoanExceptions { get; set; }
        public DbSet<LoanRepaymentScriptExclusion_Feb_3_2017> LoanRepaymentScriptExclusion_Feb_3_2017 { get; set; }
        public DbSet<LogonServersLog> LogonServersLogs { get; set; }
        public DbSet<LTEBuyBack> LTEBuyBacks { get; set; }
        public DbSet<LTEBuyBack_Broadcast> LTEBuyBack_Broadcast { get; set; }
        public DbSet<LTEBuyBackAgent> LTEBuyBackAgents { get; set; }
        public DbSet<LteBuyBackCode> LteBuyBackCodes { get; set; }
        public DbSet<LTEBuyBackLocation> LTEBuyBackLocations { get; set; }
        public DbSet<LTEBuyBakcode> LTEBuyBakcodes { get; set; }
        public DbSet<LTEBuyBakcomm> LTEBuyBakcomms { get; set; }
        public DbSet<LTEFUTFeedback> LTEFUTFeedbacks { get; set; }
        public DbSet<mobilepayment> mobilepayments { get; set; }
        public DbSet<ModemCost> ModemCosts { get; set; }
        public DbSet<ModemList> ModemLists { get; set; }
        public DbSet<ModemQty> ModemQties { get; set; }
        public DbSet<MultiplePaymentPromoCustomer> MultiplePaymentPromoCustomers { get; set; }
        public DbSet<MultiplePaymentPromoLog> MultiplePaymentPromoLogs { get; set; }
        public DbSet<OnlineCustomerEntry> OnlineCustomerEntries { get; set; }
        public DbSet<OnlineCustomerEntries_backup_061016> OnlineCustomerEntries_backup_061016 { get; set; }
        public DbSet<onlinepayment> onlinepayments { get; set; }
        public DbSet<onlinepayment_Archive_1> onlinepayment_Archive_1 { get; set; }
        public DbSet<onlinepayment_Archive_2> onlinepayment_Archive_2 { get; set; }
        public DbSet<OnlineSession> OnlineSessions { get; set; }
        public DbSet<PartnerLogin> PartnerLogins { get; set; }
        public DbSet<pop> pops { get; set; }
        public DbSet<pops_backup_050615> pops_backup_050615 { get; set; }
        public DbSet<pops_old> pops_old { get; set; }
        public DbSet<PortaCustomer> PortaCustomers { get; set; }
        public DbSet<PortaOneQuery> PortaOneQueries { get; set; }
        public DbSet<PortaOneQueries_Archive_2995376> PortaOneQueries_Archive_2995376 { get; set; }
        public DbSet<PortaOneSession> PortaOneSessions { get; set; }
        public DbSet<PortaOneTransactionNote> PortaOneTransactionNotes { get; set; }
        public DbSet<PortaOneTransactionNotes_Archive_2880914> PortaOneTransactionNotes_Archive_2880914 { get; set; }
        public DbSet<postrapayment> postrapayments { get; set; }
        public DbSet<ProductIdealFor> ProductIdealFors { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Products_View_Mapping> Products_View_Mapping { get; set; }
        public DbSet<ProductTiming> ProductTimings { get; set; }
        public DbSet<PromoDetail> PromoDetails { get; set; }
        public DbSet<PROMONOROLLOVEREXPIRYFIX> PROMONOROLLOVEREXPIRYFIXes { get; set; }
        public DbSet<PromoNoRolloverLog> PromoNoRolloverLogs { get; set; }
        public DbSet<PromoPartner> PromoPartners { get; set; }
        public DbSet<PromoPlansExclusionList> PromoPlansExclusionLists { get; set; }
        public DbSet<PromoPlansExclusionListLog> PromoPlansExclusionListLogs { get; set; }
        public DbSet<ReceiptDetail> ReceiptDetails { get; set; }
        public DbSet<ReceiptNumber> ReceiptNumbers { get; set; }
        public DbSet<Referral> Referrals { get; set; }
        public DbSet<SelfcareHit> SelfcareHits { get; set; }
        public DbSet<ServicePlanChangePromoLog> ServicePlanChangePromoLogs { get; set; }
        public DbSet<ServicePlanChange> ServicePlanChanges { get; set; }
        public DbSet<ServicePlanChanges_bkp_111016> ServicePlanChanges_bkp_111016 { get; set; }
        public DbSet<ServiceSchedule> ServiceSchedules { get; set; }
        public DbSet<SERVICESCHEDULES_BKP_230218> SERVICESCHEDULES_BKP_230218 { get; set; }
        public DbSet<ServiceSchedules_COPY> ServiceSchedules_COPY { get; set; }
        public DbSet<SignUp_Exceptionals> SignUp_Exceptionals { get; set; }
        public DbSet<SIM> SIMS { get; set; }
        public DbSet<SIMSInventory> SIMSInventories { get; set; }
        public DbSet<SIMSInventory_bk> SIMSInventory_bk { get; set; }
        public DbSet<SIMSInventory_bkp_121115> SIMSInventory_bkp_121115 { get; set; }
        public DbSet<SIMSInventory_bkup_14052015> SIMSInventory_bkup_14052015 { get; set; }
        public DbSet<SIMSInventory_new_25000> SIMSInventory_new_25000 { get; set; }
        public DbSet<SIMSInventory_UPLOAD_121115> SIMSInventory_UPLOAD_121115 { get; set; }
        public DbSet<SIMSInventory_UPLOAD_190218> SIMSInventory_UPLOAD_190218 { get; set; }
        public DbSet<SIMSUpload> SIMSUploads { get; set; }
        public DbSet<SingleAuto_Allocate_Subscribers> SingleAuto_Allocate_Subscribers { get; set; }
        public DbSet<SMPPSMSLog> SMPPSMSLogs { get; set; }
        public DbSet<SMSSender> SMSSenders { get; set; }
        public DbSet<SMSSender_Archive_300415> SMSSender_Archive_300415 { get; set; }
        public DbSet<SMSSender_Archive_5490711> SMSSender_Archive_5490711 { get; set; }
        public DbSet<SMSSender_Archive_8251147> SMSSender_Archive_8251147 { get; set; }
        public DbSet<SMSSender_Checker> SMSSender_Checker { get; set; }
        public DbSet<SocialMediaBilling> SocialMediaBillings { get; set; }
        public DbSet<SocialMediaFan> SocialMediaFans { get; set; }
        public DbSet<SocialMediaPotential> SocialMediaPotentials { get; set; }
        public DbSet<SocialMediaPromoBilling> SocialMediaPromoBillings { get; set; }
        public DbSet<SocialMediaPromoCode> SocialMediaPromoCodes { get; set; }
        public DbSet<Special_Discount_Products> Special_Discount_Products { get; set; }
        public DbSet<SSBAddOnService> SSBAddOnServices { get; set; }
        public DbSet<swap_id_030516> swap_id_030516 { get; set; }
        public DbSet<SWAP_ID_2_030516> SWAP_ID_2_030516 { get; set; }
        public DbSet<swift_staff_accounts> swift_staff_accounts { get; set; }
        public DbSet<swift_staff_internet> swift_staff_internet { get; set; }
        public DbSet<SwiftBillingPermittedServer> SwiftBillingPermittedServers { get; set; }
        public DbSet<SwiftDay_Subscribers> SwiftDay_Subscribers { get; set; }
        public DbSet<SwiftISWErrorLog> SwiftISWErrorLogs { get; set; }
        public DbSet<SwiftISWFailedPayment> SwiftISWFailedPayments { get; set; }
        public DbSet<SwiftISWPayment> SwiftISWPayments { get; set; }
        public DbSet<SwiftISWPayment_Codes> SwiftISWPayment_Codes { get; set; }
        public DbSet<SwiftISWPaymentItem> SwiftISWPaymentItems { get; set; }
        public DbSet<SwiftISWRequeryLog> SwiftISWRequeryLogs { get; set; }
        public DbSet<SwiftISWRequestLog> SwiftISWRequestLogs { get; set; }
        public DbSet<SwiftVoucherBatch> SwiftVoucherBatches { get; set; }
        public DbSet<SwiftVoucher> SwiftVouchers { get; set; }
        public DbSet<SwiftVoucherTransactionHistory> SwiftVoucherTransactionHistories { get; set; }
        public DbSet<SwiftWindowsService> SwiftWindowsServices { get; set; }
        public DbSet<SystemParameter> SystemParameters { get; set; }
        public DbSet<SystemParameters_backup_231016> SystemParameters_backup_231016 { get; set; }
        public DbSet<TARIFF_ROSE> TARIFF_ROSE { get; set; }
        public DbSet<tbl_ModemName> tbl_ModemName { get; set; }
        public DbSet<TermsandConditionsRespons> TermsandConditionsResponses { get; set; }
        public DbSet<TEST_LTEBuyBakcomm> TEST_LTEBuyBakcomm { get; set; }
        public DbSet<Timer_Reminders> Timer_Reminders { get; set; }
        public DbSet<tmp_lastpayment> tmp_lastpayment { get; set; }
        public DbSet<TMP_MAC_ADDRESSES> TMP_MAC_ADDRESSES { get; set; }
        public DbSet<TMP_MAC_ADDRESSES_2> TMP_MAC_ADDRESSES_2 { get; set; }
        public DbSet<TransactionHistory> TransactionHistories { get; set; }
        public DbSet<tSocialMediaPromoCode> tSocialMediaPromoCodes { get; set; }
        public DbSet<UsedSocialMediaPromoCode> UsedSocialMediaPromoCodes { get; set; }
        public DbSet<UserDefinedCustomer> UserDefinedCustomers { get; set; }
        public DbSet<voip_plan_mapping> voip_plan_mapping { get; set; }
        public DbSet<VOIPRelease_Reminders> VOIPRelease_Reminders { get; set; }
        public DbSet<Voucher> Vouchers { get; set; }
        public DbSet<Vouchers_bk> Vouchers_bk { get; set; }
        public DbSet<WiMAXswapOutAgent> WiMAXswapOutAgents { get; set; }
        public DbSet<WiMAXswapOutCustomer> WiMAXswapOutCustomers { get; set; }
        public DbSet<WiMAXswapOutCustomers_05052016> WiMAXswapOutCustomers_05052016 { get; set; }
        public DbSet<WiMAXswapOutLocation> WiMAXswapOutLocations { get; set; }
        public DbSet<WiMAXswapOutUniqueRefCode_Pool> WiMAXswapOutUniqueRefCode_Pool { get; set; }
        public DbSet<xmas_ecard_base> xmas_ecard_base { get; set; }
        public DbSet<t_custlastpay> t_custlastpay { get; set; }
        public DbSet<t_custlastpay2> t_custlastpay2 { get; set; }
        public DbSet<vCustPaymentExceptLast> vCustPaymentExceptLasts { get; set; }
        public DbSet<vLastCustPayment> vLastCustPayments { get; set; }
        public DbSet<vLastCustPaymentLevel2> vLastCustPaymentLevel2 { get; set; }
        public DbSet<vwCheck_for_SwiftVouchers> vwCheck_for_SwiftVouchers { get; set; }
        public DbSet<vwCheck_for_Vouchers> vwCheck_for_Vouchers { get; set; }
        public DbSet<vwCustomersEmailMessageLog> vwCustomersEmailMessageLogs { get; set; }
        public DbSet<vwonlinepayment> vwonlinepayments { get; set; }
        public DbSet<vwSMSSender> vwSMSSenders { get; set; }
    
        public virtual ObjectResult<CCPoratal_LoadPostponementbyDate_Result> CCPoratal_LoadPostponementbyDate(Nullable<int> days, string exactdate)
        {
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            var exactdateParameter = exactdate != null ?
                new ObjectParameter("exactdate", exactdate) :
                new ObjectParameter("exactdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CCPoratal_LoadPostponementbyDate_Result>("CCPoratal_LoadPostponementbyDate", daysParameter, exactdateParameter);
        }
    
        public virtual int CreateTempTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateTempTables");
        }
    
        public virtual int DeleteExpiredSessions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteExpiredSessions");
        }
    
        public virtual ObjectResult<EnterpriseEnquiries_Result> EnterpriseEnquiries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EnterpriseEnquiries_Result>("EnterpriseEnquiries");
        }
    
        public virtual int fetch_ExpiredKYC(Nullable<int> customerid, Nullable<int> days, Nullable<int> accumulate)
        {
            var customeridParameter = customerid.HasValue ?
                new ObjectParameter("customerid", customerid) :
                new ObjectParameter("customerid", typeof(int));
    
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            var accumulateParameter = accumulate.HasValue ?
                new ObjectParameter("accumulate", accumulate) :
                new ObjectParameter("accumulate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fetch_ExpiredKYC", customeridParameter, daysParameter, accumulateParameter);
        }
    
        public virtual int GenerateVoucherPIN(string pin, Nullable<float> value, Nullable<int> batchid, ObjectParameter returnVal)
        {
            var pinParameter = pin != null ?
                new ObjectParameter("pin", pin) :
                new ObjectParameter("pin", typeof(string));
    
            var valueParameter = value.HasValue ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(float));
    
            var batchidParameter = batchid.HasValue ?
                new ObjectParameter("batchid", batchid) :
                new ObjectParameter("batchid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateVoucherPIN", pinParameter, valueParameter, batchidParameter, returnVal);
        }
    
        public virtual int GetHashCode(string input, ObjectParameter hash)
        {
            var inputParameter = input != null ?
                new ObjectParameter("input", input) :
                new ObjectParameter("input", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetHashCode", inputParameter, hash);
        }
    
        public virtual int GetMajorVersion(ObjectParameter p_ver)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetMajorVersion", p_ver);
        }
    
        public virtual ObjectResult<LoadPostponementbyDate_Result> LoadPostponementbyDate(Nullable<int> days)
        {
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoadPostponementbyDate_Result>("LoadPostponementbyDate", daysParameter);
        }
    
        public virtual ObjectResult<string> PortaOneTransactionNotes_FormUID(string uid, string paymentCategory, string paymentType, string source, string partner, string transID, string parentID)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var paymentCategoryParameter = paymentCategory != null ?
                new ObjectParameter("paymentCategory", paymentCategory) :
                new ObjectParameter("paymentCategory", typeof(string));
    
            var paymentTypeParameter = paymentType != null ?
                new ObjectParameter("paymentType", paymentType) :
                new ObjectParameter("paymentType", typeof(string));
    
            var sourceParameter = source != null ?
                new ObjectParameter("source", source) :
                new ObjectParameter("source", typeof(string));
    
            var partnerParameter = partner != null ?
                new ObjectParameter("partner", partner) :
                new ObjectParameter("partner", typeof(string));
    
            var transIDParameter = transID != null ?
                new ObjectParameter("transID", transID) :
                new ObjectParameter("transID", typeof(string));
    
            var parentIDParameter = parentID != null ?
                new ObjectParameter("parentID", parentID) :
                new ObjectParameter("parentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PortaOneTransactionNotes_FormUID", uidParameter, paymentCategoryParameter, paymentTypeParameter, sourceParameter, partnerParameter, transIDParameter, parentIDParameter);
        }
    
        public virtual int promo_bonus(Nullable<int> cust_id, Nullable<double> amount)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("promo_bonus", cust_idParameter, amountParameter);
        }
    
        public virtual int TempGetAppID(string appName, ObjectParameter appId)
        {
            var appNameParameter = appName != null ?
                new ObjectParameter("appName", appName) :
                new ObjectParameter("appName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempGetAppID", appNameParameter, appId);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItem(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockDate, ObjectParameter lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItem", idParameter, itemShort, locked, lockDate, lockCookie);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItem2(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockAge, ObjectParameter lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItem2", idParameter, itemShort, locked, lockAge, lockCookie);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItem3(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockAge, ObjectParameter lockCookie, ObjectParameter actionFlags)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItem3", idParameter, itemShort, locked, lockAge, lockCookie, actionFlags);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItemExclusive(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockDate, ObjectParameter lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItemExclusive", idParameter, itemShort, locked, lockDate, lockCookie);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItemExclusive2(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockAge, ObjectParameter lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItemExclusive2", idParameter, itemShort, locked, lockAge, lockCookie);
        }
    
        public virtual ObjectResult<byte[]> TempGetStateItemExclusive3(string id, ObjectParameter itemShort, ObjectParameter locked, ObjectParameter lockAge, ObjectParameter lockCookie, ObjectParameter actionFlags)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("TempGetStateItemExclusive3", idParameter, itemShort, locked, lockAge, lockCookie, actionFlags);
        }
    
        public virtual int TempGetVersion(ObjectParameter ver)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempGetVersion", ver);
        }
    
        public virtual int TempInsertStateItemLong(string id, byte[] itemLong, Nullable<int> timeout)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemLongParameter = itemLong != null ?
                new ObjectParameter("itemLong", itemLong) :
                new ObjectParameter("itemLong", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempInsertStateItemLong", idParameter, itemLongParameter, timeoutParameter);
        }
    
        public virtual int TempInsertStateItemShort(string id, byte[] itemShort, Nullable<int> timeout)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemShortParameter = itemShort != null ?
                new ObjectParameter("itemShort", itemShort) :
                new ObjectParameter("itemShort", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempInsertStateItemShort", idParameter, itemShortParameter, timeoutParameter);
        }
    
        public virtual int TempInsertUninitializedItem(string id, byte[] itemShort, Nullable<int> timeout)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemShortParameter = itemShort != null ?
                new ObjectParameter("itemShort", itemShort) :
                new ObjectParameter("itemShort", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempInsertUninitializedItem", idParameter, itemShortParameter, timeoutParameter);
        }
    
        public virtual int TempReleaseStateItemExclusive(string id, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempReleaseStateItemExclusive", idParameter, lockCookieParameter);
        }
    
        public virtual int TempRemoveStateItem(string id, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempRemoveStateItem", idParameter, lockCookieParameter);
        }
    
        public virtual int TempResetTimeout(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempResetTimeout", idParameter);
        }
    
        public virtual int TempUpdateStateItemLong(string id, byte[] itemLong, Nullable<int> timeout, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemLongParameter = itemLong != null ?
                new ObjectParameter("itemLong", itemLong) :
                new ObjectParameter("itemLong", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempUpdateStateItemLong", idParameter, itemLongParameter, timeoutParameter, lockCookieParameter);
        }
    
        public virtual int TempUpdateStateItemLongNullShort(string id, byte[] itemLong, Nullable<int> timeout, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemLongParameter = itemLong != null ?
                new ObjectParameter("itemLong", itemLong) :
                new ObjectParameter("itemLong", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempUpdateStateItemLongNullShort", idParameter, itemLongParameter, timeoutParameter, lockCookieParameter);
        }
    
        public virtual int TempUpdateStateItemShort(string id, byte[] itemShort, Nullable<int> timeout, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemShortParameter = itemShort != null ?
                new ObjectParameter("itemShort", itemShort) :
                new ObjectParameter("itemShort", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempUpdateStateItemShort", idParameter, itemShortParameter, timeoutParameter, lockCookieParameter);
        }
    
        public virtual int TempUpdateStateItemShortNullLong(string id, byte[] itemShort, Nullable<int> timeout, Nullable<int> lockCookie)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var itemShortParameter = itemShort != null ?
                new ObjectParameter("itemShort", itemShort) :
                new ObjectParameter("itemShort", typeof(byte[]));
    
            var timeoutParameter = timeout.HasValue ?
                new ObjectParameter("timeout", timeout) :
                new ObjectParameter("timeout", typeof(int));
    
            var lockCookieParameter = lockCookie.HasValue ?
                new ObjectParameter("lockCookie", lockCookie) :
                new ObjectParameter("lockCookie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TempUpdateStateItemShortNullLong", idParameter, itemShortParameter, timeoutParameter, lockCookieParameter);
        }
    
        public virtual ObjectResult<TopupCustomers_Result> TopupCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopupCustomers_Result>("TopupCustomers");
        }
    
        public virtual ObjectResult<TopupCustomers_new_Result> TopupCustomers_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopupCustomers_new_Result>("TopupCustomers_new");
        }
    
        public virtual ObjectResult<WiMaxCustomers_Result> WiMaxCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WiMaxCustomers_Result>("WiMaxCustomers");
        }
    
        public virtual ObjectResult<EnterpriseNotOnDomain_Result> EnterpriseNotOnDomain()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EnterpriseNotOnDomain_Result>("EnterpriseNotOnDomain");
        }
    
        public virtual ObjectResult<TopupCustomers_new1_Result> TopupCustomers_new1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopupCustomers_new1_Result>("TopupCustomers_new1");
        }
    
        public virtual ObjectResult<vpn_customers_Result> vpn_customers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vpn_customers_Result>("vpn_customers");
        }
    
        public virtual ObjectResult<WiMaxProducts_Result> WiMaxProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WiMaxProducts_Result>("WiMaxProducts");
        }
    
        public virtual int InsertBatch(string batch, Nullable<int> number, string creator, string comment, Nullable<int> voucherType, ObjectParameter returnVal)
        {
            var batchParameter = batch != null ?
                new ObjectParameter("batch", batch) :
                new ObjectParameter("batch", typeof(string));
    
            var numberParameter = number.HasValue ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(int));
    
            var creatorParameter = creator != null ?
                new ObjectParameter("creator", creator) :
                new ObjectParameter("creator", typeof(string));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var voucherTypeParameter = voucherType.HasValue ?
                new ObjectParameter("voucherType", voucherType) :
                new ObjectParameter("voucherType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertBatch", batchParameter, numberParameter, creatorParameter, commentParameter, voucherTypeParameter, returnVal);
        }
    
        public virtual int ActivateVoucher(Nullable<int> voucheridFrom, Nullable<int> voucherstat, string activator, Nullable<int> voucheridTo, ObjectParameter returnVal)
        {
            var voucheridFromParameter = voucheridFrom.HasValue ?
                new ObjectParameter("voucheridFrom", voucheridFrom) :
                new ObjectParameter("voucheridFrom", typeof(int));
    
            var voucherstatParameter = voucherstat.HasValue ?
                new ObjectParameter("voucherstat", voucherstat) :
                new ObjectParameter("voucherstat", typeof(int));
    
            var activatorParameter = activator != null ?
                new ObjectParameter("activator", activator) :
                new ObjectParameter("activator", typeof(string));
    
            var voucheridToParameter = voucheridTo.HasValue ?
                new ObjectParameter("voucheridTo", voucheridTo) :
                new ObjectParameter("voucheridTo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActivateVoucher", voucheridFromParameter, voucherstatParameter, activatorParameter, voucheridToParameter, returnVal);
        }
    
        public virtual int DeActivateVoucher(Nullable<int> voucheridFrom, string deactivator, Nullable<int> voucheridTo, ObjectParameter returnVal)
        {
            var voucheridFromParameter = voucheridFrom.HasValue ?
                new ObjectParameter("voucheridFrom", voucheridFrom) :
                new ObjectParameter("voucheridFrom", typeof(int));
    
            var deactivatorParameter = deactivator != null ?
                new ObjectParameter("deactivator", deactivator) :
                new ObjectParameter("deactivator", typeof(string));
    
            var voucheridToParameter = voucheridTo.HasValue ?
                new ObjectParameter("voucheridTo", voucheridTo) :
                new ObjectParameter("voucheridTo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeActivateVoucher", voucheridFromParameter, deactivatorParameter, voucheridToParameter, returnVal);
        }
    
        public virtual int createUser(string partner_name, string username, string password, string role, string status, ObjectParameter returnVal)
        {
            var partner_nameParameter = partner_name != null ?
                new ObjectParameter("partner_name", partner_name) :
                new ObjectParameter("partner_name", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createUser", partner_nameParameter, usernameParameter, passwordParameter, roleParameter, statusParameter, returnVal);
        }
    
        public virtual int ChangeUserRole(string username, string role, ObjectParameter returnVal)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeUserRole", usernameParameter, roleParameter, returnVal);
        }
    
        public virtual int DisableUser(string username, string status, ObjectParameter returnVal)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DisableUser", usernameParameter, statusParameter, returnVal);
        }
    
        public virtual int ChangePassword(string password, string username, ObjectParameter returnVal)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangePassword", passwordParameter, usernameParameter, returnVal);
        }
    }
}
