//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpirationDate_InvalidExtensions
    {
        public int OccurenceID { get; set; }
        public Nullable<int> i_customer { get; set; }
        public string macAddress { get; set; }
        public Nullable<int> i_account { get; set; }
        public Nullable<int> i_product { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> activation_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<double> cust_balance { get; set; }
        public Nullable<double> account_balance { get; set; }
        public Nullable<System.DateTime> DateChecked { get; set; }
        public Nullable<int> Adjusted { get; set; }
        public Nullable<System.DateTime> new_activation_date { get; set; }
        public Nullable<System.DateTime> new_expiration_date { get; set; }
        public Nullable<int> AdjustedBy { get; set; }
        public string AdjustedByName { get; set; }
        public Nullable<System.DateTime> DateAdjusted { get; set; }
    }
}
