//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotlinedFundedAccountsSessionExtension
    {
        public int i_customer { get; set; }
        public string macaddress { get; set; }
        public Nullable<int> i_account { get; set; }
        public Nullable<System.DateTime> ExtensionDate { get; set; }
        public Nullable<int> i_active_callleg { get; set; }
        public Nullable<int> Sessions { get; set; }
    }
}
