//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interswitch_Paydirect
    {
        public int PaydirectID { get; set; }
        public string subscriberid { get; set; }
        public string customername { get; set; }
        public string servicetype { get; set; }
        public Nullable<float> amount { get; set; }
        public string paymentdate { get; set; }
        public string status { get; set; }
        public string cardnumber { get; set; }
        public string cardbank { get; set; }
        public string TransLocation { get; set; }
        public string IPAddress { get; set; }
        public string TransactionID { get; set; }
    }
}
