//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternetTest_Feedback
    {
        public int FeedbackID { get; set; }
        public string EmailAddress { get; set; }
        public string FullName { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> Que1Radio { get; set; }
        public string Que1Text { get; set; }
        public Nullable<int> Que2Radio { get; set; }
        public string Que2Text { get; set; }
        public Nullable<int> Que3Radio { get; set; }
        public string Que3Text { get; set; }
        public string Que4Radio { get; set; }
        public string Que5Radio { get; set; }
        public string Que6Ping1 { get; set; }
        public string Que6Ping2 { get; set; }
        public string Que6Ping3 { get; set; }
        public string Que6Download1 { get; set; }
        public string Que6Download2 { get; set; }
        public string Que6Download3 { get; set; }
        public string Que6Upload1 { get; set; }
        public string Que6Upload2 { get; set; }
        public string Que6Upload3 { get; set; }
        public string Que7Radio { get; set; }
        public string Que8Text { get; set; }
        public string EntryIPAddress { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> Submitted { get; set; }
        public string SubmissionIPAddress { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
    }
}
