//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterSwitch_Data
    {
        public int ID { get; set; }
        public int Customer_ID { get; set; }
        public string Upload_Status { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
