//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IrokoTVCode_Exceptions
    {
        public int IrokoCodeID { get; set; }
        public Nullable<int> i_customer { get; set; }
        public string PaymentReference { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> ServicePlanID { get; set; }
        public Nullable<double> AmountPaid { get; set; }
    }
}
