//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYCBlockUnbock
    {
        public int KYCBlockID { get; set; }
        public Nullable<int> i_customer { get; set; }
        public Nullable<int> i_account { get; set; }
        public Nullable<System.DateTime> DateBlocked { get; set; }
        public Nullable<int> BlockID { get; set; }
        public Nullable<int> Unblocked { get; set; }
        public Nullable<System.DateTime> DateUnblocked { get; set; }
    }
}
