//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYCDeferment
    {
        public int KYCDeferID { get; set; }
        public int i_customer { get; set; }
        public System.DateTime DatePushed { get; set; }
        public int DaysDeferred { get; set; }
        public Nullable<int> Repushed { get; set; }
        public Nullable<System.DateTime> DateRepushed { get; set; }
        public string Source { get; set; }
    }
}
