//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTEBuyBack_Broadcast
    {
        public int ID { get; set; }
        public string i_customer { get; set; }
        public string customer_name { get; set; }
        public string ref_code { get; set; }
        public string cluster { get; set; }
        public string msisdn { get; set; }
        public string IMEI { get; set; }
        public string IMSI { get; set; }
        public string servicePlan { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public string LTEType { get; set; }
        public string churnReason { get; set; }
        public string remarks { get; set; }
        public string supportKYC { get; set; }
        public string salesKYC { get; set; }
        public string ModemStatus { get; set; }
        public string ModemcollectedBy { get; set; }
        public string PaidBy { get; set; }
        public string AmountPaid { get; set; }
        public Nullable<System.DateTime> collectedOn { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
        public string customerPaid { get; set; }
        public Nullable<int> codeUsed { get; set; }
        public Nullable<int> SalescodeUsed { get; set; }
    }
}
