//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTEFUTFeedback
    {
        public int ID { get; set; }
        public int i_customer { get; set; }
        public string Question1a { get; set; }
        public string Question1b { get; set; }
        public string Question2 { get; set; }
        public string Question3 { get; set; }
        public string Question4 { get; set; }
        public string Question5a { get; set; }
        public string Question5b { get; set; }
        public string Question5c { get; set; }
        public string Question6 { get; set; }
        public Nullable<int> Question7 { get; set; }
        public Nullable<double> Question8Ping1 { get; set; }
        public Nullable<double> Question8Ping2 { get; set; }
        public Nullable<double> Question8Ping3 { get; set; }
        public Nullable<double> Question8Download1 { get; set; }
        public Nullable<double> Question8Download2 { get; set; }
        public Nullable<double> Question8Download3 { get; set; }
        public Nullable<double> Question8Upload1 { get; set; }
        public Nullable<double> Question8Upload2 { get; set; }
        public Nullable<double> Question8Upload3 { get; set; }
        public string Question9 { get; set; }
        public string Question10 { get; set; }
        public string Question11 { get; set; }
        public string Question12 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string IPCreated { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public Nullable<int> Sent { get; set; }
        public string IPSent { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
    }
}
