//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModemList
    {
        public int Id { get; set; }
        public string path { get; set; }
        public string ModemImg { get; set; }
        public string ModemType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Status { get; set; }
    }
}
