//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModemCost
    {
        public string ModemType { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> DisCost { get; set; }
        public Nullable<double> DisPayAmount { get; set; }
        public Nullable<int> DisplayOnline { get; set; }
        public string CPESeries { get; set; }
        public Nullable<int> isLTE { get; set; }
        public Nullable<bool> InStock { get; set; }
    }
}
