//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineSession
    {
        public int SessionID { get; set; }
        public Nullable<int> i_Customer { get; set; }
        public Nullable<System.DateTime> Session_Start { get; set; }
        public Nullable<int> Closed { get; set; }
        public string Session_Ref { get; set; }
    }
}
