//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerLogin
    {
        public int PartnerID { get; set; }
        public string Partner_Name { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string IPAddress { get; set; }
        public string Role { get; set; }
        public string Status { get; set; }
    }
}
