//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortaCustomer
    {
        public int i_customer { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string baddr1 { get; set; }
        public string phone1 { get; set; }
        public string email { get; set; }
        public string state { get; set; }
        public string country { get; set; }
    }
}
