//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class postrapayment
    {
        public string ID { get; set; }
        public string CLD { get; set; }
        public System.DateTime CONNECT_TIME { get; set; }
        public string ACCOUNT_ID { get; set; }
        public Nullable<float> CHARGED_Amount { get; set; }
        public Nullable<int> I_CUSTOMER { get; set; }
        public Nullable<int> I_ACCOUNT { get; set; }
    }
}
