//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoNoRolloverLog
    {
        public int LogID { get; set; }
        public int i_customer { get; set; }
        public int i_account { get; set; }
        public string macaddress { get; set; }
        public int billing_model { get; set; }
        public int Category { get; set; }
        public Nullable<System.DateTime> OldExpirationDate { get; set; }
        public Nullable<System.DateTime> NewExpirationDate { get; set; }
        public Nullable<double> OldBalance { get; set; }
        public Nullable<double> NewBalance { get; set; }
        public System.DateTime LogDate { get; set; }
    }
}
