//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoDetail
    {
        public int PromoDetaiID { get; set; }
        public int PartnerID { get; set; }
        public string PromoApp { get; set; }
        public double PartnerModemDiscount { get; set; }
        public Nullable<double> PartnerSubscriptionDiscount { get; set; }
        public double CustomerDiscount { get; set; }
    }
}
