//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMONOROLLOVEREXPIRYFIX
    {
        public decimal I_LOG { get; set; }
        public System.DateTime LOG_TIME { get; set; }
        public string IP { get; set; }
        public string TABLE_NAME { get; set; }
        public string LINE { get; set; }
        public string comment { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> I_ENV { get; set; }
        public Nullable<decimal> I_USER { get; set; }
        public string PARENT_KEY { get; set; }
        public string PARENT_TABLE { get; set; }
        public string REALM { get; set; }
        public string USERNAME { get; set; }
    }
}
