//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public int ReceiptID { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<int> i_customer { get; set; }
        public string ReceiptContent { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string LogoName { get; set; }
        public string TableName { get; set; }
        public string TableFieldName { get; set; }
        public string TableFieldValue { get; set; }
    }
}
