//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public int ReferralID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> i_customer { get; set; }
        public string ReferralCode { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ReferreeID { get; set; }
        public string Source { get; set; }
        public string Username { get; set; }
        public Nullable<int> CRMSuccess { get; set; }
        public Nullable<System.DateTime> DateUsed { get; set; }
        public string Trans_ID { get; set; }
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ContactMyFriend { get; set; }
        public Nullable<float> ReferrerShare { get; set; }
        public Nullable<float> ReferredShare { get; set; }
        public string ShareUpdatedBy { get; set; }
        public Nullable<System.DateTime> DateShareUpdated { get; set; }
        public Nullable<float> ReferrerAmount { get; set; }
        public Nullable<float> ReferredAmount { get; set; }
        public Nullable<int> Credited { get; set; }
        public Nullable<System.DateTime> DateCredited { get; set; }
        public string SourceSharedUpdated { get; set; }
        public Nullable<int> Paid { get; set; }
        public string Platform { get; set; }
        public string PlatformRef { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public string PaidBy { get; set; }
        public string PaymentID { get; set; }
        public string PaymentSource { get; set; }
        public string PromoCode { get; set; }
        public Nullable<float> PromoPercent { get; set; }
        public Nullable<int> Referrer_ProductID { get; set; }
        public Nullable<int> Referree_ProductID { get; set; }
        public string Referrer_ProductName { get; set; }
        public string Referree_ProductName { get; set; }
        public string Referrer_XDR { get; set; }
        public string Referree_XDR { get; set; }
        public string Referrer_CRMRecNo { get; set; }
        public string Referred_CRMRecNo { get; set; }
        public Nullable<int> Billing_Called { get; set; }
        public Nullable<int> Activated { get; set; }
        public Nullable<System.DateTime> DateActivated { get; set; }
        public string paymentUID { get; set; }
        public string CreditedBy { get; set; }
    }
}
