//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfcareHit
    {
        public long id { get; set; }
        public string ip_address { get; set; }
        public string page_url { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
