//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePlanChanges_bkp_111016
    {
        public int Change_ID { get; set; }
        public int Customer_ID { get; set; }
        public int Account_ID { get; set; }
        public Nullable<int> InitialPlan_ID { get; set; }
        public int NewPlan_ID { get; set; }
        public float Charged_Unused_Balance { get; set; }
        public float Account_Balance { get; set; }
        public float Topup_Amount { get; set; }
        public System.DateTime Change_Date { get; set; }
        public string Source { get; set; }
        public string Status { get; set; }
        public string OnlineID { get; set; }
        public Nullable<int> SDChanged { get; set; }
        public string apaymentUID { get; set; }
        public string cpaymentUID { get; set; }
    }
}
