//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSchedules_COPY
    {
        public int ScheduleID { get; set; }
        public string ServiceName { get; set; }
        public string MethodName { get; set; }
        public Nullable<int> Interval { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> NextRunTime { get; set; }
        public Nullable<System.DateTime> StartTimespan { get; set; }
        public Nullable<int> StartInterval { get; set; }
        public string StartType { get; set; }
        public string RunPeriod { get; set; }
        public Nullable<System.DateTime> LastRunTime { get; set; }
        public Nullable<int> exactTiming { get; set; }
        public string StartTimeexactTiming { get; set; }
    }
}
