//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignUp_Exceptionals
    {
        public int SignUpID { get; set; }
        public int i_product { get; set; }
        public Nullable<int> SingleUserValidity { get; set; }
        public Nullable<int> MultiUserValidity { get; set; }
        public Nullable<double> SingleUserModem { get; set; }
        public Nullable<double> MultiUserModem { get; set; }
        public int TradeIn { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateSetUp { get; set; }
    }
}
