//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleAuto_Allocate_Subscribers
    {
        public int SettingID { get; set; }
        public Nullable<int> i_customer { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateSet { get; set; }
        public string IP { get; set; }
        public string History { get; set; }
    }
}
