//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMPPSMSLog
    {
        public int ID { get; set; }
        public System.DateTime Log_Date { get; set; }
        public Nullable<System.DateTime> Send_Date { get; set; }
        public string Destination_Number { get; set; }
        public string Message { get; set; }
        public string Returned_Message { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Counter { get; set; }
        public string Message_ID { get; set; }
        public string SMSC_Status { get; set; }
        public Nullable<int> SMSC_Status_Code { get; set; }
        public int SMSC_Sequence { get; set; }
    }
}
