//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSender_Archive_8251147
    {
        public string SMSID { get; set; }
        public int SMS_ID { get; set; }
        public System.DateTime Send_Date { get; set; }
        public string Destination_Number { get; set; }
        public string Message { get; set; }
        public string Returned_Code { get; set; }
        public string Returned_Message { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> Sent_Date { get; set; }
        public string Called_URL { get; set; }
        public Nullable<int> Counter { get; set; }
        public Nullable<int> i_customer { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> MessagePages { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
