//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMediaPromoBilling
    {
        public Nullable<int> i_customer { get; set; }
        public int PromoId { get; set; }
        public Nullable<int> i_account { get; set; }
        public string id { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public Nullable<System.DateTime> activation_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<System.DateTime> last_usage { get; set; }
        public string fullname { get; set; }
        public string code { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
    }
}
