//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special_Discount_Products
    {
        public int ID { get; set; }
        public Nullable<int> i_product { get; set; }
        public Nullable<int> Threshold { get; set; }
        public string Pattern { get; set; }
        public Nullable<int> RepeatPattern { get; set; }
        public Nullable<int> Status { get; set; }
        public string Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
