//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSBAddOnService
    {
        public int ServiceID { get; set; }
        public Nullable<int> i_customer { get; set; }
        public string ServiceType { get; set; }
        public string StoreName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string RefNo { get; set; }
        public string Password { get; set; }
    }
}
