//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwiftVoucherTransactionHistory
    {
        public int TransactionID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string OnlineID { get; set; }
    }
}
