//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwiftISWPayment
    {
        public int PaymentID { get; set; }
        public string PaymentLogId { get; set; }
        public Nullable<int> CustReference { get; set; }
        public string AlternateCustReference { get; set; }
        public Nullable<float> Amount { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentReference { get; set; }
        public string TerminalId { get; set; }
        public string ChannelName { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ISWPaymentDate { get; set; }
        public string PaymentDate { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string InstitutionId { get; set; }
        public string InstitutionName { get; set; }
        public string BranchName { get; set; }
        public string BankName { get; set; }
        public string CustomerName { get; set; }
        public string OtherCustomerInfo { get; set; }
        public string ReceiptNo { get; set; }
        public string CollectionsAccount { get; set; }
        public string BankCode { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string DepositorName { get; set; }
        public string DepositSlipNumber { get; set; }
        public string PaymentCurrency { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<decimal> IsReversal { get; set; }
        public Nullable<System.DateTime> ReversalDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string ErrorDesc { get; set; }
        public Nullable<float> SuccessAmount { get; set; }
        public Nullable<float> SuccessDiscount { get; set; }
        public Nullable<int> CRMSuccess { get; set; }
        public string CRMErrorDesc { get; set; }
        public Nullable<System.DateTime> SwiftPaymentDate { get; set; }
        public string cXDR { get; set; }
        public string aXDR { get; set; }
        public string accountDets { get; set; }
        public string Partner { get; set; }
        public Nullable<int> BillingUpdated { get; set; }
        public Nullable<int> i_account { get; set; }
        public Nullable<int> i_product { get; set; }
        public string macAddress { get; set; }
        public string ProductName { get; set; }
        public string paymentUID { get; set; }
        public string R_paymentUID { get; set; }
        public Nullable<double> R_Amount { get; set; }
        public Nullable<int> R_Status { get; set; }
        public Nullable<System.DateTime> R_Date { get; set; }
        public string IPAddress { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<System.DateTime> AllocationEffectiveDate { get; set; }
        public Nullable<System.DateTime> AllocationExpirationDate { get; set; }
        public Nullable<double> AllocatedAmount { get; set; }
        public Nullable<int> Requeried { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<double> IncentiveAmount { get; set; }
        public string ServerIP { get; set; }
    }
}
