//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwiftISWRequeryLog
    {
        public int LogID { get; set; }
        public Nullable<System.DateTime> CallTime { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseDesc { get; set; }
        public Nullable<int> ResponseCount { get; set; }
    }
}
