//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwiftISWPaymentItem
    {
        public int PaymentItemID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public Nullable<float> ItemAmount { get; set; }
        public Nullable<int> BillingUpdated { get; set; }
    }
}
