//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwiftWindowsService
    {
        public int ID { get; set; }
        public string ServiceName { get; set; }
        public string DeploymentStatus { get; set; }
        public string TestAccounts { get; set; }
        public string Description { get; set; }
        public string RunInterval { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    }
}
