//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwiftDay_Subscribers
    {
        public int SubscriberID { get; set; }
        public Nullable<int> i_customer { get; set; }
        public Nullable<int> i_account { get; set; }
        public Nullable<int> i_product { get; set; }
        public Nullable<float> balance { get; set; }
        public Nullable<int> remDays { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
        public string ipaddress { get; set; }
        public Nullable<int> status { get; set; }
        public string OnlineID { get; set; }
        public Nullable<int> SDChanged { get; set; }
        public string paymentUID { get; set; }
        public string R_paymentUID { get; set; }
        public Nullable<double> R_Amount { get; set; }
        public Nullable<int> R_Status { get; set; }
        public Nullable<System.DateTime> R_Date { get; set; }
    }
}
