//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class swift_staff_internet
    {
        public string id { get; set; }
        public string i_account { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string dept { get; set; }
        public double Amount { get; set; }
        public string i_customer { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> next_due_date { get; set; }
        public Nullable<byte> active { get; set; }
    }
}
