//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwiftISWFailedPayment
    {
        public int FailedID { get; set; }
        public string XMLContent { get; set; }
        public string RequestDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<System.DateTime> DateCredited { get; set; }
        public string ErrorMessage { get; set; }
    }
}
