//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARIFF_ROSE
    {
        public string DESTINATION { get; set; }
        public decimal I_TARIFF { get; set; }
        public string TNAME { get; set; }
        public decimal I_DEST { get; set; }
        public string NAME { get; set; }
        public string ISO_3166_1_A2 { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PRICE_1 { get; set; }
        public decimal PRICE_N { get; set; }
        public System.DateTime EFFECTIVE_FROM { get; set; }
    }
}
