//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermsandConditionsRespons
    {
        public int TermsID { get; set; }
        public Nullable<int> i_customer { get; set; }
        public Nullable<int> Response { get; set; }
        public Nullable<System.DateTime> DateResponded { get; set; }
        public string Source { get; set; }
    }
}
