//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class voip_plan_mapping
    {
        public int voip_plan_mapping_id { get; set; }
        public Nullable<int> old_product { get; set; }
        public Nullable<int> new_product { get; set; }
        public string new_product_name { get; set; }
        public Nullable<int> voip_product { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
    }
}
