//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOIPRelease_Reminders
    {
        public int i_customer { get; set; }
        public int i_account { get; set; }
        public Nullable<System.DateTime> NotificationDay1_Date { get; set; }
        public Nullable<System.DateTime> NotificationDay2_Date { get; set; }
        public Nullable<System.DateTime> NotificationDay3_Date { get; set; }
        public Nullable<System.DateTime> Termination_Date { get; set; }
    }
}
