//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WiMAXswapOutUniqueRefCode_Pool
    {
        public int id { get; set; }
        public string ref_code { get; set; }
        public int flag { get; set; }
    }
}
