//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WiMAXswapOutAgent
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string other_names { get; set; }
        public string crm_uname { get; set; }
    }
}
