//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherTemplates.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WiMAXswapOutCustomer
    {
        public int id { get; set; }
        public int i_customer { get; set; }
        public string mac_addr { get; set; }
        public string ref_code { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> termination_date { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> recipient_id { get; set; }
        public string WimaxModemSwapped { get; set; }
        public string LTEModemCollected { get; set; }
        public bool flag { get; set; }
        public Nullable<double> AdditionalPayment { get; set; }
        public string SwappedBy { get; set; }
        public string CustomerName { get; set; }
        public string ServicePlan { get; set; }
        public Nullable<int> wimax_i_product { get; set; }
        public string IMEI { get; set; }
        public string SIMNo { get; set; }
        public string LteServicePlan { get; set; }
        public Nullable<int> lte_i_product { get; set; }
        public int ex_flag { get; set; }
        public string ref_code_creator { get; set; }
    }
}
